backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "/assets/images/uploads"

collections:
  - name: "menu" # Used in routes, e.g., /admin/collections/blog
    label: "Menu" # Used in the UI
    folder: "/"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }